name: Java CI

on: [push, pull_request]

jobs:
  buildJar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.2" >> $GITHUB_PATH

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew deployNet

      - name: Upload built jar file
        uses: actions/upload-artifact@v2
        with:
          name: Galaxia
          path: build/libs